org: georgedavis
app: techday-cloudone-common
service: techday-cloudone-common

frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: us-east-2
  memorySize: 128
  timeout: 300
  logRetentionInDays: 14  
  tags:
    BusinessCase: C1Common-TechDay
  stackTags:
    BusinessCase: C1Common-TechDay
  iam:
    role:
      name: techday-cloudone-common
      path: /
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 
            - 'ssm:*'
      tags:
        BusinessCase: C1Common-TechDay
  lambdaHashingVersion: 20201221

package:
  individually: true
  patterns:
  - '!**'

functions:
  c1Onboarding:
    handler: c1Onboarding.main
    description: Cloud One Onboarding module for C1Common-TechDay
    package:
      patterns:      
      - '*c1Onboarding.py'
    environment:
      awsRegion: us-east-2
      c1ApiKey: 20SmJdKTNTX6qvR3ocB5yqR1c64:7SeRbuznYwqcSKiPJsAmYtKLqRwJRp2tLvePjbgXHUD8xMBKy9gBAm9Eaj71XF26Vk
      c1UsersList: george.davis@tclabs.ca,
      c1LicenseValidationDayCount: 3
      # # Invite Player with Role logic
      # c1FullAccessPlayerEmails: george_davischettupuzha@trendmicro.com,
      # c1ReadOnlyPlayerEmails: george.davis@tclabs.ca,
  v1Onboarding:
    handler: v1Onboarding.main
    description: Vision One Onboarding module for C1Common-TechDay
    package:
      patterns:      
      - '*v1Onboarding.py'
    environment:
      awsRegion: us-east-2
      v1TrendRegion: United States      
      v1AuthToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjaWQiOiJmYjRmM2ExZC01ZTY1LTRiNjMtYWFiMS04MTU0OTA4N2EwMzEiLCJjcGlkIjoic3ZwIiwicHBpZCI6ImN1cyIsIml0IjoxNjM2MzQ5MDExLCJ1aWQiOiJnZW9yZ2UuZGF2aXNAdGNsYWJzLmNhIiwicGwiOiIiLCJldCI6MTY2Nzg4NTAxMX0.CcAsBZQFlQZhk82pfpOtBc1MqXm9FXd4y7RvEQPOGykcYVDLoZ-_Knig-_QGjw3Y52ypF_F-ornSnzqdu_X7lP8FT4C3fSgd9uqHchRD7evUw9JHC555d-PoUfHT4Kn5MuN0Djgq4rUxAIGKmRhpaQUIp8k48XaZI-zfB2tEsYoiOXzzGhiBuPIJSv7gtQGaTutyfrsCEBerMFfClsmWIR4xq5x_ZJMHCCRkLGXQZ-lZIhEnupXY1gLlZGQYhcbArApLfivxL1lfaxb7G5Gc8Ikxw7eTkhPKZzigZfhncbsgpxqOezh4dXGrCgzijD-eKQSF5sCp27gDeA8CRT57wCkQ0PCPqXBd7-_Ee0_HKJDeCA-hqxGk8flgNCpOj7UatPES9RwPZ487OEkzBkTjJ8N-oMcC9X_kVCKvTNKqZKeEvR_-6X5l7VicvE9VtmM1bXI0GgKRUtSCVdP46TecY7Su9DxzhElFbPZJEwjXOXICLkXqAbqiJuFuShd8vQujZY0fEfl4dmMcSkG7x-LseT7XLD_GkKRw9iNyY9Go5o7ACjrjAyHDtJkJ9qaKtvT4iaBng14ze9a80_lFhTH4oYSfhDGcIM8oIZxYZjHkZAaQSZqa8kfTctJ5HkpH58o0Z6Qxkx0LnbT5eYzdMdqXW0_bEXEkPf_S6JwlwsbqqX0
      v1UsersList: george.davis@tclabs.ca,
      # # Invite Player with Role logic
      # v1MasterAdminPlayerEmails: george.davis@tclabs.ca,
  verifyC1Onboarding:
    handler: verifyC1V1Onboarding.main
    description: Task 1 -  Cloud One Onboarding validation for Mission Control - C1Common-TechDay
    package:
      patterns:      
      - '*verifyC1V1Onboarding.py'
    environment:
      awsRegion: us-east-2
      ssmParametersList: /player/C1/c1OnboardingStatus,
      ssmParameterValue: Success
  verifyV1Onboarding:
    handler: verifyC1V1Onboarding.main
    description: Task 1 -  Vision One Onboarding validation for Mission Control - C1Common-TechDay
    package:
      patterns:      
      - '*verifyC1V1Onboarding.py'
    environment:
      awsRegion: us-east-2
      ssmParametersList: /player/V1/v1OnboardingStatus,
      ssmParameterValue: Success
  verifyC1V1Connectivity:
    handler: verifyC1V1Connectivity.main
    description: Task 2 - Cloud One and Vision One Connectivity checks for Mission Control - C1Common-TechDay
    package:
      patterns:      
      - '*verifyC1V1Connectivity.py'
    environment:
      awsRegion: us-east-2
      v1AuthToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjaWQiOiJmYjRmM2ExZC01ZTY1LTRiNjMtYWFiMS04MTU0OTA4N2EwMzEiLCJjcGlkIjoic3ZwIiwicHBpZCI6ImN1cyIsIml0IjoxNjM2MzQ5MDExLCJ1aWQiOiJnZW9yZ2UuZGF2aXNAdGNsYWJzLmNhIiwicGwiOiIiLCJldCI6MTY2Nzg4NTAxMX0.CcAsBZQFlQZhk82pfpOtBc1MqXm9FXd4y7RvEQPOGykcYVDLoZ-_Knig-_QGjw3Y52ypF_F-ornSnzqdu_X7lP8FT4C3fSgd9uqHchRD7evUw9JHC555d-PoUfHT4Kn5MuN0Djgq4rUxAIGKmRhpaQUIp8k48XaZI-zfB2tEsYoiOXzzGhiBuPIJSv7gtQGaTutyfrsCEBerMFfClsmWIR4xq5x_ZJMHCCRkLGXQZ-lZIhEnupXY1gLlZGQYhcbArApLfivxL1lfaxb7G5Gc8Ikxw7eTkhPKZzigZfhncbsgpxqOezh4dXGrCgzijD-eKQSF5sCp27gDeA8CRT57wCkQ0PCPqXBd7-_Ee0_HKJDeCA-hqxGk8flgNCpOj7UatPES9RwPZ487OEkzBkTjJ8N-oMcC9X_kVCKvTNKqZKeEvR_-6X5l7VicvE9VtmM1bXI0GgKRUtSCVdP46TecY7Su9DxzhElFbPZJEwjXOXICLkXqAbqiJuFuShd8vQujZY0fEfl4dmMcSkG7x-LseT7XLD_GkKRw9iNyY9Go5o7ACjrjAyHDtJkJ9qaKtvT4iaBng14ze9a80_lFhTH4oYSfhDGcIM8oIZxYZjHkZAaQSZqa8kfTctJ5HkpH58o0Z6Qxkx0LnbT5eYzdMdqXW0_bEXEkPf_S6JwlwsbqqX0
      v1ConnectedProductList: sws
      v1ApiBaseUrlSSMKey: /player/V1/v1ApiBaseUrl
  svcCatalogTrigger:
    handler: svcCatalogTrigger.main
    description: Service Catalog Trigger - C1Common-TechDay
    package:
      patterns:      
      - '*svcCatalogTrigger.py'
    environment:
      REGION_NAME: us-east-2
      FUNCTIONS_LIST: techday-cloudone-common-prod-c1Onboarding,
